trigger:
- client-csharp-v2

variables:
  buildConfiguration: 'Release'

jobs:
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: dotnet build src -c $(buildConfiguration)
  displayName: 'Run build'

- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - script: dotnet build src -c $(buildConfiguration)
    displayName: 'Run build'
  - script: dotnet test src/Algolia.Search.Test --configuration $(buildConfiguration) --logger trx
    displayName: 'Run tests'
  - script: dotnet publish --configuration $(buildConfiguration) --output $BUILD_ARTIFACTSTAGINGDIRECTORY
    displayName: 'Published'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- task: PublishBuildArtifacts@1

- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: dotnet build src -c $(buildConfiguration)
  displayName: 'Run build'
