trigger:
- client-csharp-v2

variables:
  buildConfiguration: 'Release'
  ALGOLIA_APPLICATION_ID_1:  '$(ALGOLIA_APPLICATION_ID_1)'
  ALGOLIA_APPLICATION_ID_2:  '$(ALGOLIA_APPLICATION_ID_2)'
  ALGOLIA_APPLICATION_ID_MCM:  '$(ALGOLIA_APPLICATION_ID_MCM)'
  ALGOLIA_SEARCH_KEY_1:  '$(ALGOLIA_SEARCH_KEY_1)'
  ALGOLIA_ADMIN_KEY_1:  '$(ALGOLIA_ADMIN_KEY_1)'
  ALGOLIA_ADMIN_KEY_2:  '$(ALGOLIA_ADMIN_KEY_2)'
  ALGOLIA_ADMIN_KEY_MCM:  '$(ALGOLIA_ADMIN_KEY_MCM)'

jobs:
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: dotnet build src -c $(buildConfiguration)
  displayName: 'Run build'

- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - script: dotnet build src -c $(buildConfiguration)
    displayName: 'Run build'
  - script: dotnet test src/Algolia.Search.Test --configuration $(buildConfiguration) --logger trx
    displayName: 'Unit testing'
  - task: PublishTestResults@2
    inputs:
      testRunner: VSTest
      testResultsFiles: '**/*.trx'

- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: dotnet build src -c $(buildConfiguration)
  displayName: 'Run build'
